version: "3"
services:
  mysql:
    image: mysql:5.7
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: laravel
        MYSQL_USER: laravel
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
        TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
  mysql-user:
    image: mysql:5.7
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_USER: laravel
        MYSQL_PASSWORD: password
        MYSQL_ROOT_PASSWORD: password
        TZ: "Asia/Tokyo"
    ports:
      - "3307:3306"
  my-queue:
      container_name: rabbitmq
      image: rabbitmq:3.7.4-management
      ports:
        - '127.0.0.1:5672:5672'
        - '127.0.0.1:15672:15672'
      volumes:
        - ./conf/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
        - ./conf/custom_definitions.json:/etc/rabbitmq/custom_definitions.json
